apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mwxsi2jgh-go 
  janus-idp.io/tekton: mwxsi2jgh-go
  backstage.io/kubernetes-id: mwxsi2jgh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mwxsi2jgh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  